<?xml version="1.0"?>
<doc>
    <assembly>
        <name>JuanMCillerLibrary</name>
    </assembly>
    <members>
        <member name="M:CsharpBasics.BreakContinue.FilteringOddNumbers(System.Collections.Generic.List{System.Int32})">
            <summary>
            This method filters odd numbers from the list.
            </summary>
            <param name="numbers">List of numbers</param>
            <returns>List with odd numbers</returns>
        </member>
        <member name="T:CsharpBasics.Dictionaries">
            <summary>
            Contains methods related to dictionaries.
            </summary>
        </member>
        <member name="M:CsharpBasics.Dictionaries.CreateDictionary(System.String[],System.Object[])">
            <summary>
            Creates a dictionary from arrays of keys and values.
            </summary>
            <param name="keys">Array of keys.</param>
            <param name="values">Array of values.</param>
            <returns>The dictionary containing the key-value pairs.</returns>
        </member>
        <member name="M:CsharpBasics.Dictionaries.GetListAllowedEntrants(System.Collections.Generic.List{System.Collections.Generic.Dictionary{System.String,System.Object}})">
            <summary>
            Generates a list of messages indicating whether each person is allowed to enter the club based on their name and age.
            </summary>
            <param name="people">A list of dictionaries representing people with "Name" and "Age" keys.</param>
            <returns>A list of strings containing messages about whether each person is allowed to enter the club.</returns>
        </member>
        <member name="M:CsharpBasics.ForLoop.CompareWithTarget(System.Collections.Generic.List{System.Double},System.Double)">
            <summary>
            Compare a list of numbers with a target.
            </summary>
            <param name="numbers">Numbers to compare with a target.</param>
            <param name="target">Target value.</param>
            <returns>A list of strings describing the comparison results.</returns>
        </member>
        <member name="M:CsharpBasics.IFStatement.GetTestResult(System.String,System.Double,System.Double,System.Double)">
            <summary>
            Method to get the average of a 3-test exam.
            </summary>
            <param name="student">Name of the student.</param>
            <param name="testA">First mark.</param>
            <param name="testB">Second mark.</param>
            <param name="testC">Third mark.</param>
            <returns>Result of the exam.</returns>
        </member>
        <member name="T:CsharpBasics.MyFirstNode">
            <summary>
            
            </summary>
        </member>
        <member name="M:CsharpBasics.MyFirstNode.GetDataType(System.Object)">
            <summary>
            This is our first method to retrieve the Data Type of an input.
            </summary>
            <param name="myVariable">This variable can be whatever input data type.</param>
            <returns>A C# Data type</returns>
        </member>
        <member name="T:CsharpBasics.Numbers">
            <summary>
            This is my Numbers class.
            </summary>
        </member>
        <member name="M:CsharpBasics.Numbers.ReturnMathOperation(System.Double,System.Double)">
            <summary>
            This node executes the sum and product of two values.
            </summary>
            <param name="firstValue">First value of the math operation.</param>
            <param name="lastVAlue">Second value of the math operation.</param>
            <returns>Returns a dictionary containing the sum and product of the two input values.</returns>
        </member>
        <member name="M:CsharpBasics.Strings.ConcatenateStrings(System.String,System.String)">
            <summary>
            This is a method to concatenate two strings.
            </summary>
            <param name="myString1">My first string input.</param>
            <param name="myString2">My second string input.</param>
            <returns>The result of merging two string inputs.</returns>
        </member>
        <member name="M:CsharpBasics.Strings.GetStringLength(System.String)">
            <summary>
            This code gets the length of a string.
            </summary>
            <param name="myString">String input.</param>
            <returns>Returns an integer.</returns>
        </member>
        <member name="M:CsharpBasics.Switch.SwitchStatement(System.Int32)">
            <summary>
            Method to outcome switch values.
            </summary>
            <param name="number">Number to be processed within the Switch statement.</param>
            <returns></returns>
        </member>
        <member name="M:CsharpBasics.TryCatch.CatchJuan(System.Collections.Generic.List{System.String})">
            <summary>
            Method to check if a list of names contains "Juan" and generate a result for each name.
            </summary>
            <param name="names">List of names to be checked</param>
            <returns>List of strings containing the result for each name</returns>
        </member>
        <member name="M:CsharpBasics.TryCatch.Division(System.Int32,System.Int32)">
            <summary>
            Performs division operation on two input numbers and returns the result as a string.
            </summary>
            <param name="input1">The first input number.</param>
            <param name="input2">The second input number.</param>
            <returns>A string containing the result of the division operation or an error message.</returns>
        </member>
        <member name="M:CsharpBasics.WhileLoop.PrintEvenNumbers(System.Int32)">
            <summary>
            Method to print even and odd numbers.
            </summary>
            <param name="limit"></param>
            <returns>List with all the odd and even numbers</returns>
        </member>
        <member name="T:DynamoGeometries.CreatePoint">
            <summary>
            Represents a class to create a point in Dynamo.
            </summary>
        </member>
        <member name="P:DynamoGeometries.CreatePoint.MyPoint">
            <summary>
            Gets or sets the point.
            </summary>
        </member>
        <member name="P:DynamoGeometries.CreatePoint.XCoord">
            <summary>
            Gets or sets the x-coordinate.
            </summary>
        </member>
        <member name="P:DynamoGeometries.CreatePoint.YCoord">
            <summary>
            Gets or sets the y-coordinate.
            </summary>
        </member>
        <member name="P:DynamoGeometries.CreatePoint.ZCoord">
            <summary>
            Gets or sets the z-coordinate.
            </summary>
        </member>
        <member name="M:DynamoGeometries.CreatePoint.#ctor(System.Double,System.Double,System.Double)">
            <summary>
            Private constructor to create a point.
            </summary>
            <param name="xCoord">The x coordinate.</param>
            <param name="yCoord">The y coordinate.</param>
            <param name="zCoord">The z coordinate.</param>
        </member>
        <member name="M:DynamoGeometries.CreatePoint.CreateMyPoint(System.Double,System.Double,System.Double)">
            <summary>
            Creates a new instance of the CreatePoint class.
            </summary>
            <param name="xCoord">The x coordinate of the point. Default is 0.</param>
            <param name="yCoord">The y coordinate of the point. Default is 0.</param>
            <param name="zCoord">The z coordinate of the point. Default is 0.</param>
            <returns>A CreatePoint object.</returns>
        </member>
        <member name="M:DynamoGeometries.CreatePoint.DeconstructPoint(Autodesk.DesignScript.Geometry.Point)">
            <summary>
            Deconstructs a point into its individual coordinates.
            </summary>
            <param name="point">The point to be deconstructed.</param>
            <returns>A dictionary containing the X, Y, and Z coordinates of the point.</returns>
        </member>
        <member name="T:DynamoGeometries.MyLine">
            <summary>
            Represents a line segment defined by two points.
            </summary>
        </member>
        <member name="P:DynamoGeometries.MyLine.StartPoint">
            <summary>
            Gets or sets the start point of the line segment.
            </summary>
        </member>
        <member name="P:DynamoGeometries.MyLine.EndPoint">
            <summary>
            Gets or sets the end point of the line segment.
            </summary>
        </member>
        <member name="P:DynamoGeometries.MyLine.MidPoint">
            <summary>
            Gets the midpoint of the line segment.
            </summary>
        </member>
        <member name="P:DynamoGeometries.MyLine.MySegment">
            <summary>
            Gets or sets the line segment.
            </summary>
        </member>
        <member name="P:DynamoGeometries.MyLine.Length">
            <summary>
            Gets or sets the length of the line segment.
            </summary>
        </member>
        <member name="M:DynamoGeometries.MyLine.#ctor(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)">
            <summary>
            Constructs a new instance of MyLine.
            </summary>
            <param name="startPoint">The start point of the line segment.</param>
            <param name="endPoint">The end point of the line segment.</param>
        </member>
        <member name="M:DynamoGeometries.MyLine.CreateLine(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)">
            <summary>
            Creates a new instance of MyLine with specified start and end points.
            </summary>
            <param name="startPoint">The start point of the line segment.</param>
            <param name="endPoint">The end point of the line segment.</param>
            <returns>A new instance of MyLine.</returns>
        </member>
        <member name="M:DynamoGeometries.MyLine.CreatePerpendicularAtParameter(Autodesk.DesignScript.Geometry.Line,System.Double,System.Double)">
            <summary>
            Creates a perpendicular line at the specified parameter on the given line.
            </summary>
            <param name="myLine">The original line.</param>
            <param name="myParameter">The parameter on the original line where the perpendicular line is to be obtained.</param>
            <param name="length">The length of the perpendicular line (default is 1).</param>
            <returns>A new MyLine object representing the perpendicular line.</returns>
        </member>
        <member name="M:DynamoGeometries.MyLine.GetSegmentLength(DynamoGeometries.MyLine)">
            <summary>
            Gets the length of the specified line segment.
            </summary>
            <param name="mySegment">The line segment.</param>
            <returns>The length of the line segment.</returns>
        </member>
        <member name="M:DynamoGeometries.MyLine.SetSegmentEndPoint(DynamoGeometries.MyLine,Autodesk.DesignScript.Geometry.Point)">
            <summary>
            Sets the end point of the specified line segment.
            </summary>
            <param name="mySegment">The line segment.</param>
            <param name="newEndPoint">The new end point.</param>
            <returns>The updated line segment.</returns>
        </member>
    </members>
</doc>
